config/routes.rb
Friendinvite::Application.routes.draw do
  get "invitations/create"

  get "invitations/destroy"

  resources :friendinvites

  resources :overviews

  resources :users
  
  resources :invitations, :only=> [:create, :destroy]

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  #belongs_to :invites, :class_name => "User", :foreign_key => "invitee_id"
  #belongs_to :facebookuid, :class_name => "User", :foreign_key => "inviter_id"
  #scope :accepted, where( "accepted_at is not null")

belongs_to :inviter, :class_name => "User", :foreign_key => "inviter_id"
scope :accepted, where( "accepted_at is not null")
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :invitations, :foreign_key => "inviter_id"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  
  def create
    invitation = params[:invitation]
    
    invitation["to"].each do |facebook_id|

    invitation.create!(:requestuid => invitation["request"], :inviter_id => facebook_id )
    end


  end

  def destroy
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @friendinvites = @user.invitations.accepted.count
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendinvite_helper.rb
module FriendinviteHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/overviews_helper.rb
module OverviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendinvite/index.html.erb
<h1>Listing users</h1>
<table>

  <tr>
    <th>Facebookid</th>
    <th>Invites</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.facebookid %></td>
    <td><%= user.invites %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

<h2>Invite Facebook Friends</h2>

<div id="fb-root"></div>
    <script src="http://connect.facebook.net/en_US/all.js"></script>
    <p>
      <input type="button"
        onclick="sendRequestToRecipients(); return false;"
        value="Send Request to Users Directly"
      />
      <input type="text" value="User ID" name="user_ids" />
      </p>
    <p>
    <input type="button"
      onclick="sendRequestViaMultiFriendSelector(); return false;"
      value="Send Request to Many Users with MFS"
    />
    </p>
    
    <script>
      FB.init({
        appId  : '280568748648369',
        status : true,
        cookie : true,
        oauth: true
      });

      function sendRequestToRecipients() {
        var user_ids = document.getElementsByName("user_ids")[0].value;
        FB.ui({method: 'apprequests',
          message: 'My Great Request',
          to: user_ids, 
        }, requestCallback);
      }

      function sendRequestViaMultiFriendSelector() {
        FB.ui({method: 'apprequests',
          message: 'My Great Request'
        }, requestCallback);
      }
      
      function requestCallback(response) {
        // Handle callback here
      }
    </script>

app/views/invitations/create.html.erb
<h1>Invitations#create</h1>
<p>Find me in app/views/invitations/create.html.erb</p>

app/views/invitations/destroy.html.erb
<h1>Invitations#destroy</h1>
<p>Find me in app/views/invitations/destroy.html.erb</p>

app/views/layouts/_friend_invite.erb
<h2>Invite Facebook Friends</h2>
<div id="fb-root"></div>
    <script src="http://connect.facebook.net/en_US/all.js"></script>
    
    <p>
    <input type="button"
      onclick="sendRequestViaMultiFriendSelector(); return false;"
      value="Send Request to Many Users with MFS"
    />
    </p>
    
    <script>
      FB.init({
        appId  : 280568748648369,
        status : true,
        cookie : true,
        oauth: true
      });

      function sendRequestViaMultiFriendSelector() {
        FB.ui({method: 'apprequests',
          message: 'My Great Request',
        }, requestCallback);
      }
      
      function requestCallback(response) {
		console.log(response);

		$.ajax({
		  type: 'POST',
		  url: "http://localhost:3000/invitations",
		  data: {invitation: response},
		  success: function(){console.log("Erfolg")},
		  dataType: "json"
		});
		
      }
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendinvite</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/overviews/_form.html.erb
<%= form_for(@overview) do |f| %>
  <% if @overview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@overview.errors.count, "error") %> prohibited this overview from being saved:</h2>

      <ul>
      <% @overview.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :invitee_id %><br />
    <%= f.number_field :invitee_id %>
  </div>
  <div class="field">
    <%= f.label :inviter_id %><br />
    <%= f.number_field :inviter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/overviews/edit.html.erb
<h1>Editing overview</h1>

<%= render 'form' %>

<%= link_to 'Show', @overview %> |
<%= link_to 'Back', overviews_path %>

app/views/overviews/index.html.erb
<h1>Listing overviews</h1>

<table>
  <tr>
    <th>Invitee</th>
    <th>Inviter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @overviews.each do |overview| %>
  <tr>
    <td><%= overview.invitee_id %></td>
    <td><%= overview.inviter_id %></td>
    <td><%= link_to 'Show', overview %></td>
    <td><%= link_to 'Edit', edit_overview_path(overview) %></td>
    <td><%= link_to 'Destroy', overview, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Overview', new_overview_path %>

app/views/overviews/new.html.erb
<h1>New overview</h1>

<%= render 'form' %>

<%= link_to 'Back', overviews_path %>

app/views/overviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Invitee:</b>
  <%= @overview.invitee_id %>
</p>

<p>
  <b>Inviter:</b>
  <%= @overview.inviter_id %>
</p>


<%= link_to 'Edit', edit_overview_path(@overview) %> |
<%= link_to 'Back', overviews_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :facebookid %><br />
    <%= f.number_field :facebookid %>
  </div>
  <div class="field">
    <%= f.label :invites %><br />
    <%= f.number_field :invites %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<table>

  <tr>
    <th>Facebookid</th>
    <th>Invites</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.facebookid %></td>
    <td><%= user.invites %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Facebookid:</b>
  <%= @user.facebookid %>
</p>

<p>
  <b>Invites:</b>
  <%= @user.invites %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>


<% if @friendinvites && @friendinvites < 5  %>
	<p> Du hast Einladungen verfügbar </p>
		<%= render :partial => "layouts/friend_invite" %>

	<%  else %>
		<p> Du hast KEINE Einladungen verfügbar </p>

<% end %>